#!/bin/bash
#SBATCH --job-name=kofam
#SBATCH --ntasks=480
#SBATCH --partition=atlas
#SBATCH --account=nal_genomics

echo -e "this is $1"
echo -e "start time:"
date

module load parallel hmmer/3.4 ruby

module load python/3.12.5 miniconda3/24.3.0
source activate venv-pandas

cd /project/nal_genomics/amanda.cooksey/kofamscan/kofam_scan/kofam_to_api_pipeline

bash kofam_masterscript.sh dme ../dromel/GCF_000001215.4_Release_6_plus_ISO1_MT_protein.faa dromel

echo -e "end time:"
date

